[[redirects]]
  from = "/images/:width/:file"
  to = "/.netlify/images?url=/images/:file&width=:width"
  status = 200

[[redirects]]
  from = "/juli"
  to = "https://telegra.ph/Juli-07-17"

[[redirects]]
  from = "/sph-anmeldung*"
  to = "/autosph:splat"
  status = 200
  
[[redirects]]
  from = "/pocketnc/guide"
  to = "https://docs.google.com/document/d/1FbMszZZnawZoD0UkwiEVL1WpHouSBBPSTTTbsZSNgYo"
  
[[redirects]]
  from = "/pocketnc"
  to = "https://drive.google.com/drive/folders/1eyh943sOvH1shQ9rXZEVee81TGMnhvrz"

[build]
  functions = "./functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://koeni.dev"

[[headers]]
  for = "*.br"
  [headers.values]
    Content-Encoding = "br"
    Cache-Control = "max-age=86400, stale-while-revalidate=3600"

[[headers]]
  for = "*.wasm*"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "max-age=86400, stale-while-revalidate=3600"