media_folder: "public/images"
public_folder: "images"

backend:
  name: git-gateway
  branch: main

collections:
  
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    extension: "mdx"
    format: "frontmatter"
    create: true
    delete: true
    fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Slug", name: "slug", widget: "string" }
    - { label: "Description", name: "description", widget: "text" }
    - { label: "Long Description", name: "longDescription", widget: "text", required: false }
    - { label: "Image", name: "image", widget: "image", required: false }
    - { label: "Link", name: "link", widget: "string" }
    - { label: "Tags", name: "tags", widget: "list" }
    - { label: "Date", name: "date", widget: "datetime" }
    - { label: "Category", name: "category", widget: "select", options: ["people", "tools", "games", "services"], required: false }
    - { label: "Live", name: "live", widget: "boolean", required: false }
    - { label: "Body", name: "body", widget: "markdown" }
  
  - name: "settings"
    label: "Settings"
    files:
      - file: "src/data/settings/promotedProjects.json"
        label: "Promoted Projects"
        name: "promotedProjects"
        fields:
          - label: "Large Project"
            name: "project1"
            widget: "relation"
            collection: "projects"
            searchFields: ["title", "slug"]
            valueField: "slug"
            displayFields: ["{{title}}: {{longDescription}}"]
            required: true
          - label: "Small Project 1"
            name: "project2"
            widget: "relation"
            collection: "projects"
            searchFields: ["title", "slug"]
            valueField: "slug"
            displayFields: ["{{title}}: {{longDescription}}"]
            required: true
          - label: "Small Project 2"
            name: "project3"
            widget: "relation"
            collection: "projects"
            searchFields: ["title", "slug"]
            valueField: "slug"
            displayFields: ["{{title}}: {{longDescription}}"]
            required: true
          - label: "Small Project 3"
            name: "project4"
            widget: "relation"
            collection: "projects"
            searchFields: ["title", "slug"]
            valueField: "slug"
            displayFields: ["{{title}}: {{longDescription}}"]
            required: true
