media_folder: "public/images"
public_folder: "images"

backend:
  name: git-gateway
  branch: main

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    extension: "mdx"
    format: "frontmatter"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Alternative Title", name: "alternativeTitle", widget: "string", required: false }
      - { label: "Short Title", name: "shortTitle", widget: "string", required: false }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Long Description",
          name: "longDescription",
          widget: "text",
          required: false,
        }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["people", "tools", "games", "services"],
          required: false,
        }
      - { label: "Live", name: "live", widget: "boolean", required: false }
      - { label: "Video", name: "video", widget: "string", required: false }
      - { label: "Type", name: "type", widget: "select", required: true, options: ["project", "article"] }
      - {
          label: "CTA Button Text for Promoted Project #1",
          name: "ctaLinkText",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    extension: "mdx"
    format: frontmatter
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", required: false }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["reverse-eng", "android", "hardware", "web"],
          required: false,
        }

  - name: "settings" 
    label: "Settings"
    files:
      - file: "src/data/settings/promotedProjects.json"
        label: "Promoted Projects"
        name: "promotedProjects"
        fields:
          - label: "Promoted Projects"
            name: "projects"
            widget: "list"
            summary: "{{fields.project.title}}"
            fields:
              - label: "Project"
                name: "project"
                widget: "relation"
                collection: "projects"
                searchFields: ["title", "slug"]
                valueField: "slug"
                displayFields: ["{{title}}: {{longDescription}}"]
                required: true
